version: '3.7'

services:
  kierratysavustin_db:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    restart: unless-stopped
    container_name: kierratysavustin_db

  kierratysavustin_client:
    image: kierratysavustin-local
    restart: unless-stopped
    container_name: kierratysavustin_client

  proxy:
    image: jwilder/nginx-proxy
    volumes: 
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 3001:80
    container_name: nginx