name: Push to main

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'documents/**'
      - 'README.md'

jobs:
  test:
    runs-on: ubuntu-18.04
    services:
      mongo:
        image: healthcheck/mongo
        ports:
          - 27017:27017
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: npm install client
        run: | 
          cd client
          npm install
      - name: npm install server
        run: |
          cd server
          npm install
      - name: e2e tests
        uses: cypress-io/github-action@v2
        with:
          working-directory: e2e_tests
          command: npm run test:e2e:prod
          start: npm run start:test
          wait-on: http://localhost:3001
